#ifndef APP_PINS_H
#define APP_PINS_H

/*
 * Everything board-specific lives here.
 * In CubeMX give each GPIO the "User Label" shown below; CubeMX then generates
 * <LABEL>_Pin and <LABEL>_GPIO_Port in main.h, which this project uses.
 *
 *   KP_R0..KP_R3  keypad rows     GPIO_Input,  pull-up
 *   KP_C0..KP_C2  keypad columns  GPIO_Output, open-drain, no pull, initial level HIGH
 *   LED_A, LED_B  bi-color LED    GPIO_Output, push-pull (A high = red, B high = green)
 *   VIB           vibration motor GPIO_Output, push-pull (drives the 2N2222 base)
 */
#include "main.h"

#ifndef KP_R0_Pin
#error "CubeMX user label KP_R0 is missing (see app_pins.h)"
#endif
#ifndef KP_R1_Pin
#error "CubeMX user label KP_R1 is missing (see app_pins.h)"
#endif
#ifndef KP_R2_Pin
#error "CubeMX user label KP_R2 is missing (see app_pins.h)"
#endif
#ifndef KP_R3_Pin
#error "CubeMX user label KP_R3 is missing (see app_pins.h)"
#endif
#ifndef KP_C0_Pin
#error "CubeMX user label KP_C0 is missing (see app_pins.h)"
#endif
#ifndef KP_C1_Pin
#error "CubeMX user label KP_C1 is missing (see app_pins.h)"
#endif
#ifndef KP_C2_Pin
#error "CubeMX user label KP_C2 is missing (see app_pins.h)"
#endif
#ifndef LED_A_Pin
#error "CubeMX user label LED_A is missing (see app_pins.h)"
#endif
#ifndef LED_B_Pin
#error "CubeMX user label LED_B is missing (see app_pins.h)"
#endif
#ifndef VIB_Pin
#error "CubeMX user label VIB is missing (see app_pins.h)"
#endif

/* Peripheral handles generated by CubeMX. Change the names if yours differ. */
#define APP_UART            huart2        /* ST-LINK virtual COM port (USART3 on some Nucleo-144 boards) */
#define APP_SERVO_TIM       htim2         /* 1 MHz tick, period 19999 => 50 Hz */
#define APP_SERVO_CHANNEL   TIM_CHANNEL_1

#endif
